# Kotlin https://gobley.dev/docs/bindgen#bindgen-configuration
package_name = "breez_sdk_spark.common"
cdylib_name = "breez_sdk_spark_bindings"
kotlin_multiplatform = false
kotlin_targets = ["jvm"]
kotlin_target_version = "1.9.21"
disable_java_cleaner = true

# Kotlin custom types
[custom_types.common_u128]
type_name = "BigInteger"
imports = [ "java.math.BigInteger" ]
into_custom = "BigInteger({})"
from_custom = "{}.toString()"

# https://mozilla.github.io/uniffi-rs/swift/configuration.html
[bindings.swift]
ffi_module_name = "breez_sdk_sparkFFI"
ffi_module_filename = "breez_sdk_commonFFI"
cdylib_name = "breez_sdk_spark_bindings"

[bindings.swift.custom_types.common_u128]
type_name = "BigUInt"
imports = [ "BigInt" ]
into_custom = "BigUInt(stringLiteral: {})"
from_custom = "{}.description"