# Kotlin https://gobley.dev/docs/bindgen#bindgen-configuration
package_name = "breez_sdk_spark.common"
cdylib_name = "breez_sdk_spark_bindings"
kotlin_multiplatform = false
kotlin_targets = ["jvm"]
kotlin_target_version = "1.9.21"
disable_java_cleaner = true

# Kotlin custom types
[custom_types.common_u128]
type_name = "BigInteger"
imports = [ "java.math.BigInteger" ]
into_custom = "BigInteger({})"
from_custom = "{}.toString()"

# https://mozilla.github.io/uniffi-rs/swift/configuration.html
[bindings.swift]
ffi_module_name = "breez_sdk_sparkFFI"
ffi_module_filename = "breez_sdk_commonFFI"
cdylib_name = "breez_sdk_spark_bindings"

[bindings.swift.custom_types.common_u128]
type_name = "BInt"
imports = [ "BigNumber" ]
into_custom = "BInt({})!"
from_custom = "{}.asString(radix: 10)"

[bindings.python.custom_types.CommonU128]
type_name = "int"
into_custom = "int({})"
from_custom = "str({})"

[bindings.csharp]
package_name = "breez_sdk_common"
cdylib_name = "breez_sdk_common"
namespace = "Breez.Sdk.Spark.Common"
access_modifier = "public"

[bindings.csharp.custom_types.U128]
type_name = "System.Numerics.BigInteger"
into_custom = "new System.Numerics.BigInteger({})"
from_custom = "{}.ToString()"

[bindings.typescript.customTypes.common_u128]
typeName = "bigint"
intoCustom = "BigInt({})"
fromCustom = "{}.toString()"

[bindings.go.custom_types.common_u128]
type_name = "*big.Int"
imports = [ "math/big" ]
into_custom = """
result, _ := new(big.Int).SetString({}, 10)
return result
"""
from_custom = "{}.String()"