// Generated by uniffi-bindgen-react-native
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry, NativeModules } from 'react-native';

export interface Spec extends TurboModule {
  installRustCrate(): boolean;
  cleanupRustCrate(): boolean;
}

// Detect architecture: __turboModuleProxy is set when TurboModules are enabled
const isTurboModuleEnabled =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (global as any).__turboModuleProxy != null;

export default isTurboModuleEnabled
  ? TurboModuleRegistry.getEnforcing<Spec>('BreezSdkSparkReactNative')
  : (NativeModules.BreezSdkSparkReactNative as Spec);