/**
 * Result of a domain-association verification check against the platform's
 * well-known configuration source. Mirrors the Rust `DomainAssociation`
 * enum shape so cross-language callers can handle it uniformly.
 */
export type DomainAssociation =
    | { kind: 'Associated' }
    | { kind: 'NotAssociated'; source: string; reason: string }
    | { kind: 'Skipped'; reason: string };

/**
 * Authenticator data captured at registration. `aaguid` is the 16-byte
 * Authenticator Attestation GUID (provider identifier); `backupEligible`
 * is the BE flag indicating whether the credential can sync across
 * devices. Both are `null` when the platform doesn't expose enough
 * authenticator data to extract them.
 *
 * AAGUID is unverified attestation. Use as a display hint only, never
 * for trust decisions.
 */
export interface RegisteredCredential {
    credentialId: Uint8Array;
    aaguid: Uint8Array | null;
    backupEligible: boolean | null;
}

/**
 * Thrown when `createPasskey` asks the platform to register a new
 * passkey but it refuses because an entry in `excludeCredentialIds`
 * matches a credential already on the device. Hosts should route the
 * user to the sign-in path instead of treating this as a generic
 * registration failure.
 */
export declare class PasskeyAlreadyExistsError extends Error {
    constructor(message?: string);
}

/**
 * Per-call overrides for `createPasskey`. All fields are optional;
 * omitted fields fall back to the corresponding constructor option,
 * then to the spec default (random 16-byte `userId`, ctor `userName`,
 * ctor `userDisplayName`).
 *
 * Per-call values let hosts vary registration metadata between
 * `createPasskey` invocations without reconstructing the provider
 * (which is typically a module-level singleton). Common uses:
 *   - rotating a per-wallet `userDisplayName` discriminator so the OS
 *     picker can distinguish multiple credentials on the same RP
 *   - encoding host-side wallet bookkeeping into `userId` so it
 *     round-trips on assertion via `userHandle`
 */
export interface CreatePasskeyRequest {
    /**
     * Credential IDs the authenticator must refuse to duplicate. When
     * any entry matches a credential already on the device, the browser
     * raises `InvalidStateError`, surfaced here as
     * `PasskeyAlreadyExistsError`. Defaults to none (no dedup check).
     */
    excludeCredentialIds?: Uint8Array[];

    /**
     * Override for the WebAuthn `user.id` field. Must be 1-64 bytes per
     * WebAuthn spec; throws otherwise. Defaults to a fresh
     * `crypto.getRandomValues(16)` per call.
     *
     * **Always randomize per call. Reusing a `userId` across creates
     * on the same `rpId` causes consumer authenticators to silently
     * destroy the existing credential and replace it with the new
     * one** — empirically verified on Apple Passwords (no prompt, no
     * warning, original credential's authenticator-internal PRF
     * secret is gone). Wallet / E2EE apps where the credential's PRF
     * output derives a recovery key MUST keep `userId` random per
     * call: a hardcoded value across a fresh-install + create flow
     * would silently destroy the user's prior credential and the data
     * tied to it.
     *
     * This option exists for hosts that want to know which random
     * `userId` was used (e.g., to derive a stable per-credential label
     * that's recomputable from the assertion's `userHandle` at sign-in
     * time). Pass a fresh random value generated by the host; never
     * persist and reuse one.
     */
    userId?: Uint8Array;

    /**
     * Override for the WebAuthn `user.name` field. Shown as a secondary
     * label in some passkey managers.
     */
    userName?: string;

    /**
     * Override for the WebAuthn `user.displayName` field. Primary label
     * in most pickers (iCloud Keychain, Google Password Manager).
     * Useful for per-wallet discriminators.
     */
    userDisplayName?: string;
}

/**
 * Options for constructing a PasskeyProvider.
 */
export interface PasskeyProviderOptions {
    /**
     * Relying Party ID. Must match the domain hosting your passkeys. On native
     * platforms this corresponds to the AASA / assetlinks.json domain. On web,
     * rpId must be a registrable suffix of window.location.hostname
     * for cross-platform credential sharing.
     *
     * Changing this after users have registered passkeys will make their existing
     * credentials undiscoverable, they would need to create new passkeys.
     * @default 'keys.breez.technology'
     */
    rpId?: string;

    /**
     * RP display name shown during credential registration. Only used when
     * creating new passkeys; changing it does not affect existing credentials.
     * @default 'Breez SDK'
     */
    rpName?: string;

    /**
     * User name stored with the credential, shown as a secondary label in some
     * passkey managers. Defaults to rpName. Only used during registration;
     * changing it does not affect existing credentials.
     */
    userName?: string;

    /**
     * User display name shown as the primary label in the passkey picker.
     * Defaults to userName. Only used during registration; changing it does
     * not affect existing credentials.
     */
    userDisplayName?: string;

    /**
     * When true (default), `derivePrfSeed` automatically creates a new passkey
     * if none exists for this RP ID, then retries the assertion. When false,
     * throws an error instead, letting the caller control registration
     * separately via `createPasskey()`.
     * @default true
     */
    autoRegister?: boolean;

    /**
     * When non-empty, restricts assertion (sign-in) to one of the listed
     * credential IDs. The browser refuses any other credential for this
     * RP, even if it matches the RP. Use this to bind sign-in to a
     * specific passkey the caller has registered, instead of letting
     * the browser pick any sibling credential that happens to share the
     * RP. Critical for deterministic seed derivation when multiple
     * credentials might exist for the same RP. When empty (default),
     * the browser picks any credential matching the RP.
     * @default []
     */
    allowCredentialIds?: Uint8Array[];

    /**
     * When set, narrows the create-time UI to the chosen authenticator
     * class. `'platform'` scopes registration to the local platform
     * authenticator (Touch ID / Face ID / Windows Hello / iCloud
     * Keychain), suppressing security-key and hybrid (cross-device)
     * options in the browser's chooser. `'cross-platform'` is the
     * inverse: only roaming authenticators (USB / NFC / BLE security
     * keys, hybrid). When omitted, the browser shows all available
     * authenticators.
     */
    authenticatorAttachment?: 'platform' | 'cross-platform';

    /**
     * WebAuthn L3 priority hints, applied to both create() and get()
     * public-key options. Soft signal compared to
     * `authenticatorAttachment` (which is create-only): browsers that
     * honor it surface the listed authenticator classes first;
     * browsers that ignore it fall back to default ordering. Stacks
     * with `authenticatorAttachment` on create. Pass `['client-device']`
     * to nudge platform authenticator before security-key / hybrid
     * options. The get() side is the only standards-track lever for
     * influencing the sign-in picker (since `authenticatorAttachment`
     * is not allowed there).
     */
    hints?: ('client-device' | 'security-key' | 'hybrid')[];

    /**
     * Default WebAuthn `timeout` (milliseconds) applied to every
     * create() and get() ceremony. The value surfaces as a hint to
     * the user agent; platforms still apply their own internal cap
     * (60s on iOS, similar on Android Credential Manager). Pass a
     * value 5 to 10 seconds under the platform cap so a host-side
     * "looks like a timeout" heuristic can fire before the OS
     * tears the prompt down. When undefined (default), the platform
     * default applies.
     */
    defaultTimeoutMs?: number;
}

/**
 * Built-in passkey-based PRF provider for browser environments.
 *
 * Implements the PrfProvider interface using the WebAuthn API with the PRF
 * extension (navigator.credentials.create/get).
 *
 * Uses discoverable credentials (resident keys) so no credential storage is needed.
 * On first use, if no credential exists for the RP ID, a new passkey is
 * automatically created (registered), then the assertion is retried.
 *
 * @example
 * ```typescript
 * import { Passkey } from '@breeztech/breez-sdk-spark'
 * import { PasskeyProvider } from '@breeztech/breez-sdk-spark/passkey-prf-provider'
 *
 * const prfProvider = new PasskeyProvider()
 * const passkey = new Passkey(prfProvider, undefined)
 * const wallet = await passkey.getWallet('personal')
 * ```
 */
export declare class PasskeyProvider {
    constructor(options?: PasskeyProviderOptions);

    /**
     * List of base64 credential IDs to constrain assertion to. Mirrors
     * the `allowCredentialIds` constructor option but is also settable
     * at runtime so callers can re-target sign-in to a refreshed list
     * (e.g. after a synced-storage hydrate) without reconstructing the
     * provider. Empty list (default) lets the platform pick any
     * credential matching the RP.
     */
    allowCredentialIds: Uint8Array[];

    /**
     * Settable `AbortSignal`. When set before a derivePrfSeed /
     * derivePrfSeeds / createPasskey invocation, threaded into the
     * underlying `navigator.credentials.{get,create}` call so the
     * caller can abort an in-flight ceremony.
     *
     * Mirror of the `allowCredentialIds` / `onAssertionCredentialId`
     * mutate-the-singleton pattern: per-call value, set before the
     * call, optionally cleared after. Necessary because the SDK's
     * Rust-side Passkey methods (setupWallet / getWallet) drive the
     * provider via UniFFI without a generic signal-passing slot, so
     * the host has no other place to attach the signal.
     *
     * Aborting unsettles the WebAuthn promise per spec; on iOS Safari
     * the OS modal does NOT visually close in current versions, but
     * the JS promise rejects with `AbortError` so the host can free
     * its own state machine.
     */
    currentSignal?: AbortSignal;

    /**
     * Optional callback fired with the credential ID and user handle
     * returned by every successful WebAuthn assertion (sign-in path).
     * Hosts can set this to record which credential was just used so
     * they can populate `excludeCredentialIds` and `allowCredentialIds`
     * on subsequent requests.
     *
     * Useful for:
     * - Migrating users whose passkey predates the host's own
     *   credential-ID tracking: the first successful sign-in surfaces
     *   the credential ID, after which the host's records are correct
     *   and the platform-level "already exists" check can fire on
     *   future create attempts.
     * - Retroactive rename of a credential's `user.name` /
     *   `user.displayName` via `PublicKeyCredential.signalCurrentUserDetails`,
     *   which requires the credential's `user.id` (the `userHandle`).
     *
     * The second argument may be `null` on browsers that don't return
     * `userHandle` in the assertion response (rare — most authenticators
     * include it for discoverable credentials).
     *
     * Set before calling `derivePrfSeed`. Not invoked on registration
     * (see `createPasskey`'s return value for that).
     */
    onAssertionCredentialId?: (credentialId: Uint8Array, userHandle: Uint8Array | null) => void;

    /**
     * Derive a 32-byte seed from passkey PRF with the given salt.
     *
     * Authenticates the user via a platform passkey and evaluates the PRF extension.
     * If no credential exists for this RP ID, a new passkey is created automatically.
     *
     * @param salt - The salt string to use for PRF evaluation.
     * @returns The 32-byte PRF output.
     * @throws If authentication fails, PRF is not supported, or the user cancels.
     */
    derivePrfSeed(salt: string): Promise<Uint8Array>;

    /**
     * Derive multiple 32-byte PRF outputs in as few user prompts as the
     * authenticator supports. The WebAuthn PRF extension allows two
     * salts per assertion (`prf.eval.first` + `prf.eval.second`),
     * collapsing two derivations into a single ceremony on browsers
     * that honor the spec.
     *
     * Salt count semantics:
     * - 0 salts: returns empty without prompting.
     * - 1 salt: equivalent to `derivePrfSeed`.
     * - 2 salts: 1 ceremony where supported, 2 otherwise.
     * - 3+ salts: pairs are batched. Trailing odd salt uses single-salt.
     *
     * Authenticators that silently drop the second salt fall back to a
     * sequential single-salt assertion for the affected salt(s); worst
     * case prompt count matches looping `derivePrfSeed`.
     *
     * Output ordering matches input ordering.
     *
     * @param salts - Salt strings in caller order.
     * @returns One 32-byte output per salt, in input order.
     */
    derivePrfSeeds(salts: string[]): Promise<Uint8Array[]>;

    /**
     * Create a new passkey with PRF support.
     *
     * Only registers the credential, no seed derivation. Triggers exactly
     * 1 WebAuthn prompt. Use this to separate credential creation from
     * derivation in multi-step onboarding flows.
     *
     * @param request - Per-call overrides. Passing a plain `Uint8Array[]`
     *   is accepted as a backward-compat shim for
     *   `{ excludeCredentialIds: array }` and is equivalent to the
     *   pre-`CreatePasskeyRequest` signature.
     * @returns The credential ID plus AAGUID and backup-eligibility flag
     *   parsed from the authenticator data. AAGUID and `backupEligible`
     *   are `null` on browsers that don't expose `getAuthenticatorData()`.
     * @throws {PasskeyAlreadyExistsError} If an entry in `excludeCredentialIds`
     *   matches a credential already on the device.
     * @throws If the user cancels, `userId` fails the WebAuthn 1-64 byte
     *   length validation, or PRF is not supported by the authenticator.
     */
    createPasskey(request?: CreatePasskeyRequest | Uint8Array[]): Promise<RegisteredCredential>;

    /**
     * Check if a PRF-capable passkey is available on this device.
     *
     * @returns true if WebAuthn with PRF extension is likely supported.
     */
    isPrfAvailable(): Promise<boolean>;

    /**
     * Verify the configured `rpId` is a valid scope for WebAuthn from the
     * current document's origin.
     *
     * Browsers validate `rp.id` locally at `navigator.credentials.get / create`
     * time: `rpId` must be a registrable suffix of `window.location.hostname`,
     * or equal to it. There is no AASA / assetlinks equivalent on the web,
     * no external file, no TTL, no caching.
     *
     * This method mirrors that browser-side rule so a misconfigured `rpId`
     * (e.g., a staging build pointed at `keys.breez.technology` while hosted
     * at `staging.example.com`) can be diagnosed with a concrete reason
     * before the first WebAuthn ceremony, instead of the opaque
     * `SecurityError` the browser would otherwise throw.
     *
     * @returns `Associated` when the rpId is in scope, `NotAssociated` with
     *   a concrete reason when it isn't, or `Skipped` when the check can't
     *   run (SSR / no `window.location`).
     */
    checkDomainAssociation(): Promise<DomainAssociation>;
}

/**
 * @deprecated Use PasskeyProviderOptions instead. This alias will be removed in a future release.
 */
export type PasskeyPrfProviderOptions = PasskeyProviderOptions;

/**
 * @deprecated Use PasskeyProvider instead. This alias will be removed in a future release.
 */
export { PasskeyProvider as PasskeyPrfProvider };
