/**
 * Result of a domain-association verification check against the platform's
 * well-known configuration source. Mirrors the Rust `DomainAssociation`
 * enum shape so cross-language callers can handle it uniformly.
 */
export type DomainAssociation =
    | { kind: 'Associated' }
    | { kind: 'NotAssociated'; source: string; reason: string }
    | { kind: 'Skipped'; reason: string };

/**
 * Authenticator data captured at registration. `aaguid` is the 16-byte
 * Authenticator Attestation GUID (provider identifier); `backupEligible`
 * is the BE flag indicating whether the credential can sync across
 * devices. Both are `null` when the platform doesn't expose enough
 * authenticator data to extract them.
 *
 * AAGUID is unverified attestation. Use as a display hint only, never
 * for trust decisions.
 */
export interface RegisteredCredential {
    credentialId: Uint8Array;
    aaguid: Uint8Array | null;
    backupEligible: boolean | null;
}

/**
 * Thrown when `createPasskey` asks the platform to register a new
 * passkey but it refuses because an entry in `excludeCredentialIds`
 * matches a credential already on the device. Hosts should route the
 * user to the sign-in path instead of treating this as a generic
 * registration failure.
 */
export declare class PasskeyAlreadyExistsError extends Error {
    constructor(message?: string);
}

/**
 * Per-call overrides for `createPasskey`. All fields are optional;
 * omitted fields fall back to the corresponding constructor option,
 * then to the spec default (random 16-byte `userId`, ctor `userName`,
 * ctor `userDisplayName`).
 *
 * Per-call values let hosts vary registration metadata between
 * `createPasskey` invocations without reconstructing the provider
 * (which is typically a module-level singleton). Common uses:
 *   - rotating a per-wallet `userDisplayName` discriminator so the OS
 *     picker can distinguish multiple credentials on the same RP
 *   - encoding host-side wallet bookkeeping into `userId` so it
 *     round-trips on assertion via `userHandle`
 */
export interface CreatePasskeyRequest {
    /**
     * Credential IDs the authenticator must refuse to duplicate. When
     * any entry matches a credential already on the device, the browser
     * raises `InvalidStateError`, surfaced here as
     * `PasskeyAlreadyExistsError`. Defaults to none (no dedup check).
     */
    excludeCredentialIds?: Uint8Array[];

    /**
     * Override for the WebAuthn `user.id` field. Must be 1-64 bytes per
     * WebAuthn spec; throws otherwise. Defaults to a fresh
     * `crypto.getRandomValues(16)` per call.
     *
     * **Always randomize per call. Reusing a `userId` across creates
     * on the same `rpId` causes consumer authenticators to silently
     * destroy the existing credential and replace it with the new
     * one** — empirically verified on Apple Passwords (no prompt, no
     * warning, original credential's authenticator-internal PRF
     * secret is gone). Wallet / E2EE apps where the credential's PRF
     * output derives a recovery key MUST keep `userId` random per
     * call: a hardcoded value across a fresh-install + create flow
     * would silently destroy the user's prior credential and the data
     * tied to it.
     *
     * This option exists for hosts that want to know which random
     * `userId` was used (e.g., to derive a stable per-credential label
     * that's recomputable from the assertion's `userHandle` at sign-in
     * time). Pass a fresh random value generated by the host; never
     * persist and reuse one.
     */
    userId?: Uint8Array;

    /**
     * Override for the WebAuthn `user.name` field. Shown as a secondary
     * label in some passkey managers.
     */
    userName?: string;

    /**
     * Override for the WebAuthn `user.displayName` field. Primary label
     * in most pickers (iCloud Keychain, Google Password Manager).
     * Useful for per-wallet discriminators.
     */
    userDisplayName?: string;

    /**
     * AbortSignal threaded into `navigator.credentials.create`. The
     * spec-defined late-abort race (signal aborts after the OS prompt
     * resolves) raises {@link PasskeyCreateAbortedError} carrying the
     * orphan credential's metadata so hosts can still record it.
     */
    signal?: AbortSignal;
}

/**
 * Per-call options for {@link PasskeyProvider.derivePrfSeed} and
 * {@link PasskeyProvider.derivePrfSeeds}. All fields optional.
 */
export interface DerivePrfSeedOptions {
    /**
     * Restrict assertion to one of these credential IDs. The browser
     * refuses any other credential for this RP. Use to pin sign-in to
     * a specific passkey when multiple credentials exist for the RP.
     * Empty / omitted lets the browser pick any matching credential.
     */
    allowCredentialIds?: Uint8Array[];

    /**
     * AbortSignal threaded into `navigator.credentials.get`. Aborting
     * rejects the promise with `AbortError`. iOS Safari quirk: the
     * promise rejects but the OS modal does NOT visually close.
     */
    signal?: AbortSignal;

    /**
     * Fired with the asserted credential's ID and user handle after a
     * successful ceremony. Useful for migrating credential-ID
     * tracking, or for `PublicKeyCredential.signalCurrentUserDetails`
     * follow-ups. Errors thrown inside are swallowed; the seed return
     * is never blocked.
     */
    onCredentialId?: (credentialId: Uint8Array, userHandle: Uint8Array | null) => void;
}

/**
 * Options for constructing a PasskeyProvider.
 */
export interface PasskeyProviderOptions {
    /**
     * Relying Party ID. Must match the domain hosting your passkeys. On native
     * platforms this corresponds to the AASA / assetlinks.json domain. On web,
     * rpId must be a registrable suffix of window.location.hostname
     * for cross-platform credential sharing.
     *
     * Changing this after users have registered passkeys will make their existing
     * credentials undiscoverable, they would need to create new passkeys.
     * @default 'keys.breez.technology'
     */
    rpId?: string;

    /**
     * RP display name shown during credential registration. Only used when
     * creating new passkeys; changing it does not affect existing credentials.
     * @default 'Breez SDK'
     */
    rpName?: string;

    /**
     * User name stored with the credential, shown as a secondary label in some
     * passkey managers. Defaults to rpName. Only used during registration;
     * changing it does not affect existing credentials.
     */
    userName?: string;

    /**
     * User display name shown as the primary label in the passkey picker.
     * Defaults to userName. Only used during registration; changing it does
     * not affect existing credentials.
     */
    userDisplayName?: string;

    /**
     * When true (default), `derivePrfSeed` automatically creates a new passkey
     * if none exists for this RP ID, then retries the assertion. When false,
     * throws an error instead, letting the caller control registration
     * separately via `createPasskey()`.
     * @default true
     */
    autoRegister?: boolean;

    /**
     * When set, narrows the create-time UI to the chosen authenticator
     * class. `'platform'` scopes registration to the local platform
     * authenticator (Touch ID / Face ID / Windows Hello / iCloud
     * Keychain), suppressing security-key and hybrid (cross-device)
     * options in the browser's chooser. `'cross-platform'` is the
     * inverse: only roaming authenticators (USB / NFC / BLE security
     * keys, hybrid). When omitted, the browser shows all available
     * authenticators.
     */
    authenticatorAttachment?: 'platform' | 'cross-platform';

    /**
     * WebAuthn L3 priority hints, applied to both create() and get()
     * public-key options. Soft signal compared to
     * `authenticatorAttachment` (which is create-only): browsers that
     * honor it surface the listed authenticator classes first;
     * browsers that ignore it fall back to default ordering. Stacks
     * with `authenticatorAttachment` on create. Pass `['client-device']`
     * to nudge platform authenticator before security-key / hybrid
     * options. The get() side is the only standards-track lever for
     * influencing the sign-in picker (since `authenticatorAttachment`
     * is not allowed there).
     */
    hints?: ('client-device' | 'security-key' | 'hybrid')[];

    /**
     * Default WebAuthn `timeout` (milliseconds) applied to every
     * create() and get() ceremony. The value surfaces as a hint to
     * the user agent; platforms still apply their own internal cap
     * (60s on iOS, similar on Android Credential Manager). Pass a
     * value 5 to 10 seconds under the platform cap so a host-side
     * "looks like a timeout" heuristic can fire before the OS
     * tears the prompt down. When undefined (default), the platform
     * default applies.
     */
    defaultTimeoutMs?: number;
}

/**
 * Built-in passkey-based PRF provider for browser environments.
 *
 * Implements the PrfProvider interface using the WebAuthn API with the PRF
 * extension (navigator.credentials.create/get).
 *
 * Uses discoverable credentials (resident keys) so no credential storage is needed.
 * On first use, if no credential exists for the RP ID, a new passkey is
 * automatically created (registered), then the assertion is retried.
 *
 * @example
 * ```typescript
 * import { Passkey } from '@breeztech/breez-sdk-spark'
 * import { PasskeyProvider } from '@breeztech/breez-sdk-spark/passkey-prf-provider'
 *
 * const prfProvider = new PasskeyProvider()
 * const passkey = new Passkey(prfProvider, undefined)
 * const wallet = await passkey.getWallet('personal')
 * ```
 */
export declare class PasskeyProvider {
    constructor(options?: PasskeyProviderOptions);

    /**
     * Derive a 32-byte seed from passkey PRF.
     *
     * If no credential exists and `autoRegister` is true (default), a
     * new passkey is created and the assertion is retried.
     *
     * @throws If authentication fails, PRF is not supported, or the user cancels.
     */
    derivePrfSeed(salt: string, options?: DerivePrfSeedOptions): Promise<Uint8Array>;

    /**
     * Derive multiple 32-byte PRF outputs in as few user prompts as the
     * authenticator supports. Pairs salts into `prf.eval.first` +
     * `prf.eval.second` per ceremony where the platform honors it.
     * Authenticators that drop `second` fall back to single-salt for
     * the affected salt; worst case prompt count matches looping
     * `derivePrfSeed`. Output order matches input order.
     */
    derivePrfSeeds(salts: string[], options?: DerivePrfSeedOptions): Promise<Uint8Array[]>;

    /**
     * Create a new passkey with PRF support.
     *
     * @throws {PasskeyAlreadyExistsError} If an entry in `excludeCredentialIds`
     *   matches a credential already on the device.
     * @throws {PasskeyCreateAbortedError} If `request.signal` aborts after
     *   the OS has already created the credential.
     * @throws If the user cancels, `userId` fails the WebAuthn 1-64 byte
     *   length validation, or PRF is not supported by the authenticator.
     */
    createPasskey(request?: CreatePasskeyRequest): Promise<RegisteredCredential>;

    /**
     * Check if a PRF-capable passkey is available on this device.
     *
     * @returns true if WebAuthn with PRF extension is likely supported.
     */
    isPrfAvailable(): Promise<boolean>;

    /**
     * Verify the configured `rpId` is a valid scope for WebAuthn from the
     * current document's origin.
     *
     * Browsers validate `rp.id` locally at `navigator.credentials.get / create`
     * time: `rpId` must be a registrable suffix of `window.location.hostname`,
     * or equal to it. There is no AASA / assetlinks equivalent on the web,
     * no external file, no TTL, no caching.
     *
     * This method mirrors that browser-side rule so a misconfigured `rpId`
     * (e.g., a staging build pointed at `keys.breez.technology` while hosted
     * at `staging.example.com`) can be diagnosed with a concrete reason
     * before the first WebAuthn ceremony, instead of the opaque
     * `SecurityError` the browser would otherwise throw.
     *
     * @returns `Associated` when the rpId is in scope, `NotAssociated` with
     *   a concrete reason when it isn't, or `Skipped` when the check can't
     *   run (SSR / no `window.location`).
     */
    checkDomainAssociation(): Promise<DomainAssociation>;
}

/**
 * @deprecated Use PasskeyProviderOptions instead. This alias will be removed in a future release.
 */
export type PasskeyPrfProviderOptions = PasskeyProviderOptions;

/**
 * @deprecated Use PasskeyProvider instead. This alias will be removed in a future release.
 */
export { PasskeyProvider as PasskeyPrfProvider };
