import 'dart:convert';
import 'dart:mirrors';

/// Recursively convert an FRB-generated object to a JSON-serializable structure.
///
/// Uses `dart:mirrors` to reflect public fields from plain data classes and
/// freezed sealed-class variants generated by flutter_rust_bridge.
Object? objToSerializable(Object? obj) {
  if (obj == null) return null;
  if (obj is String || obj is int || obj is double || obj is bool) return obj;
  if (obj is BigInt) return obj.toString();
  if (obj is Enum) return obj.name;
  if (obj is List) return obj.map(objToSerializable).toList();
  if (obj is Map) {
    return obj.map((k, v) => MapEntry(k.toString(), objToSerializable(v)));
  }

  // Use reflection to extract public instance fields from FRB-generated
  // classes (both plain data classes and freezed sealed-class variants).
  final mirror = reflect(obj);
  final fields = _reflectFields(mirror);
  if (fields.isNotEmpty) return fields;

  // Empty types (e.g. SyncWalletResponse with no fields).
  return <String, dynamic>{};
}

/// Walk the class hierarchy and collect all public, non-static fields.
Map<String, dynamic> _reflectFields(InstanceMirror mirror) {
  final fields = <String, dynamic>{};
  ClassMirror? current = mirror.type;

  while (current != null && current.reflectedType != Object) {
    for (final entry in current.declarations.entries) {
      final decl = entry.value;
      if (decl is VariableMirror && !decl.isStatic && !decl.isPrivate) {
        final name = MirrorSystem.getName(entry.key);
        if (!fields.containsKey(name)) {
          fields[name] = objToSerializable(
            mirror.getField(entry.key).reflectee,
          );
        }
      }
    }
    current = current.superclass;
  }

  return fields;
}

/// Serialize an object to a pretty-printed JSON string.
String serialize(Object? obj) {
  return const JsonEncoder.withIndent('  ').convert(objToSerializable(obj));
}

/// Print an object as formatted JSON.
void printValue(Object? obj) {
  print(serialize(obj));
}
