use crate::Seed;

/// A wallet derived from a passkey.
///
/// Contains the derived seed and the label used during derivation.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct Wallet {
    /// The derived seed.
    pub seed: Seed,
    /// The label used for derivation (either user-provided or the default).
    pub label: String,
}

/// Request for [`crate::passkey::Passkey::setup_wallet`].
#[derive(Debug, Default, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct SetupWalletRequest {
    /// User-chosen label. Defaults to the configured default label
    /// (`PasskeyConfig::default_label`, or `"Default"` when unset) when
    /// `None`.
    #[cfg_attr(feature = "uniffi", uniffi(default = None))]
    pub label: Option<String>,
    /// Whether to publish `label` to Nostr after deriving. Pass `false`
    /// for speculative derivations (cold restore).
    #[cfg_attr(feature = "uniffi", uniffi(default = false))]
    pub publish_label: bool,

    /// Forwarded to
    /// [`crate::passkey::DeriveSeedsRequest::allow_credentials`].
    /// Useful for server-driven flows that resolve the credential set
    /// out-of-band.
    #[cfg_attr(feature = "uniffi", uniffi(default = []))]
    pub allow_credentials: Vec<Vec<u8>>,

    /// Forwarded to
    /// [`crate::passkey::DeriveSeedsRequest::prefer_immediately_available_credentials`].
    #[cfg_attr(feature = "uniffi", uniffi(default = None))]
    pub prefer_immediately_available_credentials: Option<bool>,
}

/// Response from [`crate::passkey::Passkey::setup_wallet`].
#[derive(Debug, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct WalletSetup {
    pub wallet: Wallet,
    /// Credential that derived this wallet. Absent when the provider
    /// does not surface it.
    pub credential_id: Option<Vec<u8>>,
}

/// Derived seeds plus the credential observed in the same assertion.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct DeriveSeedsOutput {
    pub seeds: Vec<Vec<u8>>,
    /// Absent when the provider does not surface it.
    pub credential_id: Option<Vec<u8>>,
}

/// A newly created passkey credential.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct RegisteredCredential {
    pub credential_id: Vec<u8>,
    /// `WebAuthn` user handle (1 to 64 bytes), generated by the
    /// provider and never host-supplied.
    pub user_id: Vec<u8>,
    /// Authenticator identifier. A display hint only, never a basis for
    /// trust decisions: this attestation is unverified.
    pub aaguid: Option<Vec<u8>>,
    pub backup_eligible: Option<bool>,
}

/// Configuration for the passkey client. The Relying Party fields apply
/// only when a binding builds the built-in provider for you; a provider
/// you construct yourself owns its own RP and ignores them.
#[derive(Debug, Default, Clone)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct PasskeyConfig {
    /// Default wallet label when a call provides none. Unset uses
    /// `"Default"`.
    #[cfg_attr(feature = "uniffi", uniffi(default = None))]
    pub default_label: Option<String>,

    /// Relying Party ID. Unset uses the Breez shared RP
    /// (`keys.breez.technology`).
    #[cfg_attr(feature = "uniffi", uniffi(default = None))]
    pub rp_id: Option<String>,

    /// Relying Party name. Unset uses `"Breez"`.
    #[cfg_attr(feature = "uniffi", uniffi(default = None))]
    pub rp_name: Option<String>,
}
