build:
	cd ../../../ && cargo xtask package wasm::all

build-node:
	cd ../../../ && cargo xtask package wasm::node

build-deno:
	cd ../../../ && cargo xtask package wasm::deno

build-web:
	cd ../../../ && cargo xtask package wasm::web

build-bundle:
	cd ../../../ && cargo xtask package wasm::bundle