[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.18"
clap = { version = "4.5", features = ["derive"] }
xshell = "0.2"
rayon = "1.10"


