// Generated by uniffi-bindgen-react-native
#include "breeztech-breez-sdk-spark-react-native.h"
#include "generated/breez_sdk_common.hpp"
#include "generated/breez_sdk_spark.hpp"
#include "generated/breez_sdk_spark_bindings.hpp"

namespace breeztech_breezsdksparkreactnative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeBreezSdkCommon::registerModule(runtime, callInvoker);
		NativeBreezSdkSpark::registerModule(runtime, callInvoker);
		NativeBreezSdkSparkBindings::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}