// Generated by uniffi-bindgen-react-native
package com.breeztech.breezsdkspark

import com.facebook.react.TurboReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfo
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.facebook.react.uimanager.ViewManager
import java.util.HashMap

class BreezSdkSparkReactNativePackage : TurboReactPackage() {
  override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? {
    return if (name == BreezSdkSparkReactNativeModule.NAME) {
      BreezSdkSparkReactNativeModule(reactContext)
    } else {
      null
    }
  }

  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider {
    return ReactModuleInfoProvider {
      val moduleInfos: MutableMap<String, ReactModuleInfo> = HashMap()
      moduleInfos[BreezSdkSparkReactNativeModule.NAME] = ReactModuleInfo(
        BreezSdkSparkReactNativeModule.NAME,
        BreezSdkSparkReactNativeModule.NAME,
        false,  // canOverrideExistingModule
        false,  // needsEagerInit
        false,  // isCxxModule
        BuildConfig.IS_NEW_ARCHITECTURE_ENABLED  // isTurboModule
      )
      moduleInfos
    }
  }

  // Old architecture compatibility - these methods are called when new arch is disabled
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
    return listOf(BreezSdkSparkReactNativeModule(reactContext))
  }

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return emptyList()
  }
}