[package]
name = "lnurl"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum = { version = "0.8.4", features = ["macros"] }
axum-extra = { version = "0.10.1" }
base64.workspace = true
bitcoin.workspace = true
clap = { workspace = true, features = ["derive"] }
figment = { workspace = true, features = ["env", "toml"] }
hex.workspace = true
lightning-invoice = { workspace = true, features = ["std"] }
lnurl-models.workspace = true
nostr = { workspace = true, features = ["nip57"] }
nostr-sdk = { workspace = true, features = ["nip57"] }
platform-utils.workspace = true
rand.workspace = true
reqwest.workspace = true
regex = "1.11.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
spark.workspace = true
spark-postgres.workspace = true
spark-wallet.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
x509-parser = { version = "0.18.0", features = ["verify"] }

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules = { workspace = true, features = ["postgres"] }

[features]
dev = []

[lints]
workspace = true
