// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "breeztech-breez-sdk-spark-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "BreezSdkSparkReactNativeSpec.h"

@interface BreezSdkSparkReactNative : NSObject <NativeBreezSdkSparkReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface BreezSdkSparkReactNative : NSObject <RCTBridgeModule>
#endif

@end