module golang-memtest

go 1.21

require breez_sdk_spark_go v0.0.0

// The generated Go bindings are in ffi/golang/ (gitignored, generated by `make bindings-golang`)
replace breez_sdk_spark_go => ../ffi/golang
