/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "BreezSdkSparkReactNativeSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeBreezSdkSparkReactNativeCxxSpecJSI_installRustCrate(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeBreezSdkSparkReactNativeCxxSpecJSI *>(&turboModule)->installRustCrate(
    rt
  );
}
static jsi::Value __hostFunction_NativeBreezSdkSparkReactNativeCxxSpecJSI_cleanupRustCrate(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeBreezSdkSparkReactNativeCxxSpecJSI *>(&turboModule)->cleanupRustCrate(
    rt
  );
}

NativeBreezSdkSparkReactNativeCxxSpecJSI::NativeBreezSdkSparkReactNativeCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("BreezSdkSparkReactNative", jsInvoker) {
  methodMap_["installRustCrate"] = MethodMetadata {0, __hostFunction_NativeBreezSdkSparkReactNativeCxxSpecJSI_installRustCrate};
  methodMap_["cleanupRustCrate"] = MethodMetadata {0, __hostFunction_NativeBreezSdkSparkReactNativeCxxSpecJSI_cleanupRustCrate};
}


} // namespace facebook::react
