rust:
  directory: ../..
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
  # Disable server-side storage features (postgres, mysql) and compile out trace-level logs to reduce binary size
  cargoExtras:
    - --no-default-features
    - --features=release-max-level-debug
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
  # Disable server-side storage features (postgres, mysql) and compile out trace-level logs to reduce binary size
  cargoExtras:
    - --no-default-features
    - --features=release-max-level-debug
turboModule:
  cpp: cpp
  ts: src