rust:
  directory: ../..
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
ios:
  useDynamicLibrary: false
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/static/RnBreezSdkSpark
  # Disable postgres feature to reduce binary size (not needed for mobile)
  cargoExtras:
    - --no-default-features
turboModule:
  cpp: cpp
  ts: src
