name: Publish Kotlin Multiplatform Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'SDK repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'Git commit, tag or branch reference'
        required: true
        type: string
      package-version:
        description: 'Version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'Should publish to maven.'
        required: true
        type: boolean
        default: false
    secrets:
      BREEZ_MVN_USERNAME:
        description: 'Username for gradlew publish'
        required: true
      BREEZ_MVN_PASSWORD:
        description: 'Password for gradlew publish'
        required: true

jobs:
  build-language-bindings:
    name: Build language bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download aarch64-linux-android
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-linux-android
          path: aarch64-linux-android

      - name: Build Kotlin Multiplatform language bindings
        working-directory: crates/breez-sdk/bindings
        run: |
          cargo install gobley-uniffi-bindgen --git https://github.com/breez/gobley --rev 72753910f54a157de2f84b78dc6f78415e28d4f2
          gobley-uniffi-bindgen --library -o ffi/kmp --crate-configs breez_sdk_spark_bindings=./uniffi.kotlin-multiplatform.toml --crate-configs breez_sdk_spark=../core/uniffi.kotlin-multiplatform.toml --crate-configs breez_sdk_common=../common/uniffi.kotlin-multiplatform.toml ../../../aarch64-linux-android/libbreez_sdk_spark_bindings.so

      - name: Archive Kotlin Multiplatform language bindings
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin-multiplatform
          path: crates/breez-sdk/bindings/ffi/kmp/*

  build-package:
    name: Build package
    runs-on: macOS-latest
    needs: build-language-bindings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download Android JNI libs
        uses: actions/download-artifact@v4
        with:
          name: bindings-android-jniLibs
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/src/androidMain/jniLibs

      - name: Download Kotlin Multiplatform bindings
        uses: actions/download-artifact@v4
        with:
          name: bindings-kotlin-multiplatform
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/src

      - name: Download aarch64-apple-ios
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-apple-ios
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/src/lib/ios-arm64

      - name: Download aarch64-apple-ios-sim
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-apple-ios-sim
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/src/lib/ios-simulator-arm64

      - name: Download x86_64-apple-ios
        uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-apple-ios
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/src/lib/ios-simulator-x64

      - name: Build Kotlin Multiplatform project
        working-directory: crates/breez-sdk/bindings/langs/kotlin-multiplatform
        env:
          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
        run: ./gradlew :breez-sdk-spark-kmp:assemble

      - name: Archive aar
        if: ${{ !inputs.publish }}
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-multiplatform-release.aar
          path: crates/breez-sdk/bindings/langs/kotlin-multiplatform/breez-sdk-spark-kmp/build/outputs/aar/breez-sdk-spark-kmp-release.aar
        
      - name: Publish artifacts
        if: ${{ inputs.publish }}
        working-directory: crates/breez-sdk/bindings/langs/kotlin-multiplatform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
          BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
        run: |
          ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"
